### ISSUE TITLE
plone.app.discussion 2.4.16. incompatible with Plone 4.3.9

### ISSUE THREAD

**Issue by mck9** [plone/plone.app.discussion#105]
after buildout

<pre>
ZopeXMLConfigurationError: File "/dev/plone/plone-4.3.9/buildout-cache/eggs/plone.app.discussion-2.4.16-py2.7.egg/plone/app/discussion/notifications.zcml", line 6.2-10.8
    ImportError: cannot import name IMailSchema
</pre>

**Comment by gforcada** [comment]
Hi @mck9 !

Since version 2.4.0 (see the changelog https://pypi.io/project/plone.app.discussion/ ) plone.app.discussion is only Plone 5 compatible.

Plone 4.3.9 pins plone.app.discussion to version 2.2.16.

So using any version later than that would be at your own risk, and as seen here, some incompatibilities to be found.

I'm closing it as 2.4.x would not be made compatible with Plone 4.3.x.

But bugs/pull requests targeting 2.2.x are welcome!

**Comment by mck9** [comment]
Good to know. The changelog makes it not clear.
