### ISSUE TITLE
Provide WXR export to allow easy migration to Disqus

### ISSUE THREAD

**Issue by saily** [plone/plone.app.discussion#86]
This would be a very nice feature to migrate to [collective.disqus](https://github.com/collective/collective.disqus). @frisi you're active on collective.disqus, do you think it would make more sense to provide a migration task there?

**Comment by frisi** [comment]
i'm using it for some sites but i'm not involved in collective.disqus development.
however, i'd vote for adding this export functionality to collective.disqus since most probably you'll be using this package after migrating your comments to disqus.
in addition p.a.discussion is a core package and the community would need to maintain a very seldom used feature.
